export const SHOW_LOADER = "SHOW_LOADER"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL"
export const GET_PATIENTS = "GET_PATIENTS"

export const ERROR = "ERROR"
